CycleCycleCycle/Models/Route.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CycleCycleCycle.Models
{
    public class Route
    {
        public int RouteID { get; set; }
        public int? AccountID { get; set; }

        public string Name { get; set; }
        [DisplayName("Date Uploaded")]
        public DateTime DateCreated { get; set; }
        public double Distance { get; set; }
        [DisplayName("Total Ascent")]
        public double TotalAscent { get; set; }
        [DisplayName("Total Descent")]
        public double TotalDescent { get; set; }
        [DisplayName("Average Rating")]
        public double? AverageRating { get; set; }

        [DisplayName("Uploaded By")]
        public virtual Account Account { get; set; }
        public virtual ICollection<RoutePoint> RoutePoints { get; set; }
        public virtual ICollection<RouteReview> RouteReviews { get; set; }
        public virtual ICollection<Favourite> Favourites { get; set; }
        public virtual ICollection<Ride> Rides { get; set; } 

    }
}

CycleCycleCycle/Controllers/RouteController.cs
using System;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Security;
using System.Web;
using System.Web.Mvc;
using System.Xml.Linq;
using CycleCycleCycle.Models;
using CycleCycleCycle.Models.Repositories;
using CycleCycleCycle.Services;
using CycleCycleCycle.ViewModels;

namespace CycleCycleCycle.Controllers
{   
    public class RouteController : BaseController
    {
        private readonly IRouteService _routeService;
        private readonly IFavouriteService _favouriteService;

        public RouteController(IAccountService accountService, IRouteService routeService, IFavouriteService favouriteService)
            : base(accountService)
        {
            _routeService = routeService;
            _favouriteService = favouriteService;
        }

        //
        // GET: /Route/

        public ViewResult Index()
        {
            TopRoutes topRoutes = _routeService.TopRoutes(Account);
            return View(topRoutes);
        }

        //
        // GET: /Route/Details/5

        public ViewResult Details(int id)
        {
            bool isFavourited;
            bool isOwner;

            Route route = _routeService.Details(
                id,
                Request.IsAuthenticated ? (int?)Account.AccountID : null,
                out isFavourited,
                out isOwner);

            ViewBag.IsFavourited = isFavourited;
            ViewBag.IsOwner = isOwner;
            
            return View(route);
        }

        //
        // GET: /Route/PointDetails/5

        public JsonResult PointDetails(string sidx, string sord, int page, int rows, int entityId)
        {
            int totalPages;
            int totalRecords;
            var routePoints = _routeService.RoutePoints(entityId, sidx, sord, page, rows, out totalPages,
                                                        out totalRecords);

            var jsonData = new
            {
                total = totalPages,
                page,
                records = totalRecords,
                rows = (
                           from rp in routePoints
                           select new
                           {
                               id = rp.RoutePointID,
                               cell = new string[]
                                                                        {
                                                                            rp.TimeRecorded.ToString(),
                                                                            rp.Elevation.ToString(),
                                                                            rp.Latitude.ToString(),
                                                                            rp.Longitude.ToString()
                                                                        }
                           }).ToArray()
            };

            return Json(jsonData, JsonRequestBehavior.AllowGet);
        }
        
        //
        // GET: /Route/Edit/5
        [Authorize]
        public ActionResult Edit(int id)
        {
            bool isFavourite;
            bool isOwner;
            Route route = _routeService.Details(id, Account.AccountID, out isFavourite, out isOwner);
            if (!isOwner)
            {
                return RedirectToAction("Unauthorised", "Home");
            }
            return View(route);
        }

        //
        // POST: /Route/Edit/5

        [HttpPost]
        [Authorize]
        public ActionResult Edit(Route route)
        {
            if (ModelState.IsValid)
            {
                Route updatedRoute;
                try
                {
                    updatedRoute= _routeService.Update(route, Account.AccountID);
                }
                catch (SecurityException)
                {
                    return RedirectToAction("Unauthorised", "Home");
                }
                
                return RedirectToAction("Details", new { id = updatedRoute.RouteID});
            }
            return View();
        }

        //
        // GET: /Route/Upload
        [Authorize]
        public ActionResult Upload()
        {
            return View();
        }

        //
        // POST: /Route/Upload
        [HttpPost]
        [Authorize]
        public ActionResult Upload(HttpPostedFileBase file)
        {
            try
            {
                XDocument xmlDocument = XDocument.Load(file.InputStream);
                Route route = _routeService.CreateFromXDocument(xmlDocument, Account.AccountID);
                return RedirectToAction("Details", new {id = route.RouteID});
            }
            catch (Exception)
            {
                ModelState.AddModelError("", "Uploaded file is not a valid GPX file");
                return View();
            }
        }

        //
        // GET: /Route/HeightMapImage
        public FileResult HeightMapImage(int id, int width, int height)
        {
            Bitmap bitmap = _routeService.HeightMapImage(id, width, height);
            MemoryStream memoryStream = new MemoryStream();
            bitmap.Save(memoryStream, ImageFormat.Png);

            return File(memoryStream.ToArray(), "image/png");
        }

        public ActionResult Find()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Find(RouteSearch search)
        {
            try
            {
                string name;
                search.Results = _routeService.FindRoute(search.SearchText, 10, out name);
                search.SearchedLocation = name;
            }
            catch(Exception)
            {
                ModelState.AddModelError("", "An error has occurred, unable to retrieve search results.");
            }
            
            return View(search);
        }

        [HttpPost]
        [Authorize]
        public JsonResult Favourite(int id)
        {
            _favouriteService.Favourite(Account.AccountID, id);
            return Json(true);
        }

        [HttpPost]
        [Authorize]
        public JsonResult Unfavourite(int id)
        {
            _favouriteService.Unfavourite(Account.AccountID, id);
            return Json(true);
        }

        public FileResult Download(int id)
        {
            string filename;
            FileResult result = new FileStreamResult(_routeService.Download(id, out filename), "application/xml");
            result.FileDownloadName = filename;
            return result;
        }
    }
}

CycleCycleCycle/Views/Route/Delete.cshtml
@model CycleCycleCycle.Models.Route

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Route</legend>

    <div class="display-label">Name</div>
    <div class="display-field">@Model.Name</div>

    <div class="display-label">DateCreated</div>
    <div class="display-field">@String.Format("{0:g}", Model.DateCreated)</div>

    <div class="display-label">Account</div>
    <div class="display-field">@Html.DisplayTextFor(_ => Model.Account).ToString()</div>

    <div class="display-label">RoutePoints</div>
    <div class="display-field">@(Model.RoutePoints == null ? "None" : Model.RoutePoints.Count.ToString())</div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

CycleCycleCycle/Views/Route/Edit.cshtml
@model CycleCycleCycle.Models.Route

@{
    ViewBag.Title = "Edit";
}

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    
    @Html.HiddenFor(model => model.RouteID)
	@Html.Partial("_CreateOrEdit", Model)

    <input type="submit" class="btn primary" value="Save" /> @Html.ActionLink("Cancel", "Details", new { id = Model.RouteID }, new { Class="btn"})
}

CycleCycleCycle/Views/Route/Find.cshtml
@model CycleCycleCycle.ViewModels.RouteSearch

@{
    ViewBag.Title = "Find";
}

@using(Html.BeginForm("Find", "Route")) {
<div class="areaBlock">
    <span>Find Route</span>
    <span>@Html.EditorFor(m => m.SearchText)</span>
    <span><input type="submit" value="Search" class="btn primary" /></span>
</div>
}
@if (Model.Results != null)
{
    if (Model.Results.Count > 0)
    {
        <p>Results for @Model.SearchedLocation</p>
        <table class="zebra-striped">
            <tr>
                <th>Name</th>
                <th>Distance From Start</th>
                <th>Created By</th>
            </tr>
            @foreach (var result in Model.Results)
            {
                <tr>
                    <td>@Html.ActionLink(result.Name, "Details", new {id = result.RouteID})</td>
                    <td>@Html.LongDistance(result.DistanceFromStart)</td>
                    <td>@Html.Encode(result.CreatedBy)</td>
                </tr>
            }
        </table>
    }
    else
    {
        <p>No results found near @Model.SearchedLocation</p>
    }
}

CycleCycleCycle/Views/Route/Index.cshtml
@model CycleCycleCycle.ViewModels.TopRoutes

@{
    ViewBag.Title = "Routes";
}

<script type="text/javascript">
    $(document).ready(function () {
        var recentlyUploadedTab = $("#recentlyUploadedTab");
        var recentlyUploadedPage = $("#recentlyUploadedPage");
        var highestRatedTab = $("#highestRatedTab");
        var highestRatedPage = $("#highestRatedPage");

        function activateTab(tab) {
            if (tab === recentlyUploadedTab) {
                recentlyUploadedTab.addClass("active");
                recentlyUploadedPage.show();
            }
            else {
                recentlyUploadedTab.removeClass("active");
                recentlyUploadedPage.hide();
            }

            if (tab === highestRatedTab) {
                highestRatedTab.addClass("active");
                highestRatedPage.show();
            }
            else {
                highestRatedTab.removeClass("active");
                highestRatedPage.hide();
            }
        }

        recentlyUploadedTab.click(function (event) {
            activateTab(recentlyUploadedTab);
            event.preventDefault();
        });
        highestRatedTab.click(function(event) {
            activateTab(highestRatedTab);
            event.preventDefault();
        });
    })
</script>

@Html.Partial("_FindRoutePartial")
<ul class="tabs">
    <li class="active" id="recentlyUploadedTab"><a href="#">Recently Uploaded</a></li>
    <li id="highestRatedTab"><a href="#">Highest Rated</a></li>
</ul>
<div id="recentlyUploadedPage">
    @Html.Partial("_RouteListPartial", Model.RecentlyUploaded)
</div>
<div id="highestRatedPage" style="display:none;">
    @Html.Partial("_RouteListPartial", Model.HighestRated)
</div>

CycleCycleCycle/Views/Route/PointDetails.cshtml
@model IEnumerable<CycleCycleCycle.Models.RoutePoint>

<table>
    <tr>
        <th>
            Longitude
        </th>
        <th>
            Latitude
        </th>
        <th>
            Elevation
        </th>
        <th>
            Time Recorded
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Longitude)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Latitude)
        </td>
        <td>
            @Html.Distance(item.Elevation)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TimeRecorded)
        </td>
    </tr>
}

</table>

CycleCycleCycle/Views/Route/Upload.cshtml
@{
    ViewBag.Title = "Upload";
}

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
<div class="page-header">
    <h1>Upload <small>Select a GPX file to upload</small></h1>
</div>
@Html.Partial("_UploadPartial")

CycleCycleCycle/Views/Route/_CreateOrEdit.cshtml
@model CycleCycleCycle.Models.Route

@* This partial view defines form fields that will appear when creating and editing entities *@

<div class="row">
    @Html.LabelFor(model => model.Name) @Html.EditorFor(model => model.Name) @Html.ValidationMessageFor(model => model.Name)
</div>
<div class="breaker"></div>