CycleCycleCycle/Controllers/RouteController.cs
using System;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Security;
using System.Web;
using System.Web.Mvc;
using System.Xml.Linq;
using CycleCycleCycle.Models;
using CycleCycleCycle.Models.Repositories;
using CycleCycleCycle.Services;
using CycleCycleCycle.ViewModels;

namespace CycleCycleCycle.Controllers
{   
    public class RouteController : BaseController
    {
        private readonly IRouteService _routeService;
        private readonly IFavouriteService _favouriteService;

        public RouteController(IAccountService accountService, IRouteService routeService, IFavouriteService favouriteService)
            : base(accountService)
        {
            _routeService = routeService;
            _favouriteService = favouriteService;
        }

        //
        // GET: /Route/

        public ViewResult Index()
        {
            TopRoutes topRoutes = _routeService.TopRoutes(Account);
            return View(topRoutes);
        }

        //
        // GET: /Route/Details/5

        public ViewResult Details(int id)
        {
            bool isFavourited;
            bool isOwner;

            Route route = _routeService.Details(
                id,
                Request.IsAuthenticated ? (int?)Account.AccountID : null,
                out isFavourited,
                out isOwner);

            ViewBag.IsFavourited = isFavourited;
            ViewBag.IsOwner = isOwner;
            
            return View(route);
        }

        //
        // GET: /Route/PointDetails/5

        public JsonResult PointDetails(string sidx, string sord, int page, int rows, int entityId)
        {
            int totalPages;
            int totalRecords;
            var routePoints = _routeService.RoutePoints(entityId, sidx, sord, page, rows, out totalPages,
                                                        out totalRecords);

            var jsonData = new
            {
                total = totalPages,
                page,
                records = totalRecords,
                rows = (
                           from rp in routePoints
                           select new
                           {
                               id = rp.RoutePointID,
                               cell = new string[]
                                                                        {
                                                                            rp.TimeRecorded.ToString(),
                                                                            rp.Elevation.ToString(),
                                                                            rp.Latitude.ToString(),
                                                                            rp.Longitude.ToString()
                                                                        }
                           }).ToArray()
            };

            return Json(jsonData, JsonRequestBehavior.AllowGet);
        }
        
        //
        // GET: /Route/Edit/5
        [Authorize]
        public ActionResult Edit(int id)
        {
            bool isFavourite;
            bool isOwner;
            Route route = _routeService.Details(id, Account.AccountID, out isFavourite, out isOwner);
            if (!isOwner)
            {
                return RedirectToAction("Unauthorised", "Home");
            }
            return View(route);
        }

        //
        // POST: /Route/Edit/5

        [HttpPost]
        [Authorize]
        public ActionResult Edit(Route route)
        {
            if (ModelState.IsValid)
            {
                Route updatedRoute;
                try
                {
                    updatedRoute= _routeService.Update(route, Account.AccountID);
                }
                catch (SecurityException)
                {
                    return RedirectToAction("Unauthorised", "Home");
                }
                
                return RedirectToAction("Details", new { id = updatedRoute.RouteID});
            }
            return View();
        }

        //
        // GET: /Route/Upload
        [Authorize]
        public ActionResult Upload()
        {
            return View();
        }

        //
        // POST: /Route/Upload
        [HttpPost]
        [Authorize]
        public ActionResult Upload(HttpPostedFileBase file)
        {
            try
            {
                XDocument xmlDocument = XDocument.Load(file.InputStream);
                Route route = _routeService.CreateFromXDocument(xmlDocument, Account.AccountID);
                return RedirectToAction("Details", new {id = route.RouteID});
            }
            catch (Exception)
            {
                ModelState.AddModelError("", "Uploaded file is not a valid GPX file");
                return View();
            }
        }

        //
        // GET: /Route/HeightMapImage
        public FileResult HeightMapImage(int id, int width, int height)
        {
            Bitmap bitmap = _routeService.HeightMapImage(id, width, height);
            MemoryStream memoryStream = new MemoryStream();
            bitmap.Save(memoryStream, ImageFormat.Png);

            return File(memoryStream.ToArray(), "image/png");
        }

        public ActionResult Find()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Find(RouteSearch search)
        {
            try
            {
                string name;
                search.Results = _routeService.FindRoute(search.SearchText, 10, out name);
                search.SearchedLocation = name;
            }
            catch(Exception)
            {
                ModelState.AddModelError("", "An error has occurred, unable to retrieve search results.");
            }
            
            return View(search);
        }

        [HttpPost]
        [Authorize]
        public JsonResult Favourite(int id)
        {
            _favouriteService.Favourite(Account.AccountID, id);
            return Json(true);
        }

        [HttpPost]
        [Authorize]
        public JsonResult Unfavourite(int id)
        {
            _favouriteService.Unfavourite(Account.AccountID, id);
            return Json(true);
        }

        public FileResult Download(int id)
        {
            string filename;
            FileResult result = new FileStreamResult(_routeService.Download(id, out filename), "application/xml");
            result.FileDownloadName = filename;
            return result;
        }
    }
}

CycleCycleCycle/Controllers/RouteReviewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CycleCycleCycle.Models;
using CycleCycleCycle.Models.Repositories;
using CycleCycleCycle.Services;

namespace CycleCycleCycle.Controllers
{
    public class RouteReviewController : BaseController
    {
        private readonly IRouteService _routeService;
        private readonly IRouteReviewService _routeReviewService;

        public RouteReviewController(IAccountService accountService, IRouteService routeService, IRouteReviewService routeReviewService) : base(accountService)
        {
            _routeService = routeService;
            _routeReviewService = routeReviewService;
        }

        //
        // GET: /RouteReview/Create/5
        [Authorize]
        public ActionResult Create(int id)
        {
            ViewBag.RouteName = _routeService.Details(id).Name;
            RouteReview review = new RouteReview();
            review.RouteID = id;
            review.Rating = 3;
            return View(review);
        }

        [Authorize]
        [HttpPost]
        public ActionResult Create(RouteReview routeReview)
        {            
            if (ModelState.IsValid)
            {
                if (_routeReviewService.IsRouteReviewedByUser(routeReview.RouteID, Account.AccountID))
                {
                    ModelState.AddModelError("", "You have already written a review for this route.");
                    return View(routeReview);
                }

                routeReview.AccountID = Account.AccountID;
                routeReview = _routeReviewService.Insert(routeReview);

                return RedirectToAction("Details", "Route", new { id = routeReview.RouteID });
            }
            else
            {
                ViewBag.RouteName = _routeService.Details(routeReview.RouteID).Name;
                return View(routeReview);
            }
        }

    }
}

CycleCycleCycle/Views/Shared/_FindRoutePartial.cshtml
@using(Html.BeginForm("Find", "Route")) {
<div class="areaBlock">
    <span>Find Route</span>
    <span>@Html.TextBox("SearchText")</span>
    <span><input type="submit" value="Search" class="btn primary" /></span>
    <span style="float:right;">@Html.ActionLink("Upload Route", "Upload", "Route", null, new { Class = "btn"})</span>
</div>
}

CycleCycleCycle/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>CycleCycleCycle - @ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/ui.jqgrid.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/jquery-ui-1.8.16.custom.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/SiteExtensions.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.5.1.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/modernizr-1.7.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/grid.locale-en.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.jqGrid.min.js")" type="text/javascript"></script>
</head>
<body>
@{
    var controllerName = ViewContext.Controller.GetType().Name;
    string action = (string)ViewContext.Controller.ValueProvider.GetValue("action").RawValue;
    var homeClass = (controllerName == "HomeController" && action != "About") ? "active" : "";
    var routeClass = (controllerName == "RouteController") ? "active" : "";
    var aboutClass = (controllerName == "HomeController" && action == "About") ? "active" : "";
    var profileClass = (controllerName == "ProfileController") ? "active" : "";
}
     <header>
        <div class="topbar">
          <div class="container ">
            <h3><a class="logo" href="@Url.Action("Index", "Home")">
                <span>cyclecyclecycle.com</span>
            </a></h3>
            <ul>
              <li class="@homeClass">@Html.ActionLink("Home", "Index", "Home")</li>
              <li class="@routeClass">@Html.ActionLink("Routes", "Index", "Route")</li>
              @if (Request.IsAuthenticated)
              {
                  <li class="@profileClass">@Html.ActionLink("Profile", "Index", "Profile")</li>
              }
              <li class="@aboutClass">@Html.ActionLink("About", "About", "Home")</li>
            </ul>
            <ul class="nav secondary-nav">
                @Html.Partial("_LogOnPartial")
            </ul>
          </div>
        </div>
    </header>
    <section>
        <div class="breaker"></div>
        <div class="container">
            @RenderBody()
        </div>
    </section>
</body>
</html>

CycleCycleCycle/Views/Shared/_LogOnPartial.cshtml
@if(Request.IsAuthenticated) {
    <li>@Html.ActionLink("Log Off", "LogOff", "Account")</li>
}
else {
    <li>@Html.ActionLink("Register", "Register", "Account")</li>
    <li>@Html.ActionLink("Log On", "LogOn", "Account")</li>
}

CycleCycleCycle/Views/Shared/_ReviewListPartial.cshtml
@using CycleCycleCycle.Models
@model IEnumerable<CycleCycleCycle.Models.RouteReview>
           
<table class="plain">
@foreach (RouteReview review in Model)
{
    <tbody>
        <tr>
            <td>Route</td>
            <td>@Html.ActionLink(review.Route.Name, "Route", "Details", new { id = review.RouteID})</td>
        </tr>
        <tr>
            <td>Rating</td>
            <td>@Html.Rating(review.Rating)</td>
        </tr>
        <tr>
            <td>Reviewed by</td>
            <td>@Html.ActionLink(review.Account.Username, "Index", "Profile", new {id=review.Account.Username}, new {})</td>
        </tr>
        @if (!String.IsNullOrEmpty(review.Review))
        {
            <tr>
                <td>Comments</td>
                <td>@review.Review</td>
            </tr>     
        }
    </tbody>
}
</table>

CycleCycleCycle/Views/Shared/_RidesListPartial.cshtml
@model IEnumerable<CycleCycleCycle.Models.Ride>
<table class="zebra-striped">
        <tr>
            <th>
                Route
            </th>
            <th>
                Distance
            </th>
            <th>
                Date Ridden
            </th>
            <th>
                Time Taken
            </th>
        </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
			    @Html.ActionLink(item.Route.Name, "Details", "Route", new { id = item.RouteID }, null)
            </td>
            <td>
			    @Html.LongDistance(item.Route.Distance)
            </td>
            <td>
			    @item.TimeOfRide.ToString()
            </td>
            <td>
                @Html.TimeTaken(item.TimeTaken)
            </td>
        </tr>
    }

    </table>

CycleCycleCycle/Views/Shared/_RouteListPartial.cshtml
@model IEnumerable<CycleCycleCycle.ViewModels.RouteSummary>

<table class="zebra-striped">
        <tr>
            <th>
                Name
            </th>
            <th>Average Rating</th>
            <th>
                Date Created
            </th>
            <th>
                Created By
            </th>
        </tr>

    @foreach (var item in Model) {
        <tr>
            <td>
			    @Html.ActionLink(item.Name, "Details", "Route", new { id = item.RouteID}, null)
            </td>
            @if (item.Reviewed)
            {
                <td>
                     @Html.Rating(item.AverageRating)
                </td>
            }
            else
            {
                 <td>
                     @Html.Rating(item.AverageRating) (@Html.ActionLink("review", "Create", "RouteReview", new { id = item.RouteID }, null))
                 </td>  
            }
                
            <td>
			    @String.Format("{0:g}", item.DateCreated)
            </td>
            <td>
			    @Html.ActionLink(item.CreatedBy, "Index", "Profile", new {id=item.CreatedBy}, new {})
            </td>
        </tr>
    }

    </table>

CycleCycleCycle/Views/Shared/_UploadPartial.cshtml
@if (!ViewData.ModelState.IsValid) {
    <div class="row">
        <div class="span12 columns">
            <div class="alert-message error">
            <a class="close" href="#">&times;</a>
            <p>@Html.ValidationSummary()</p>
            </div>
        </div>
    </div>
}

@using (Html.BeginForm("Upload", "Route", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <input type='file' name='file' id='file' />
    <input type="submit" value="submit" class="btn primary" />
}